# Basic site info
title:              "ishikawa nakamura •••"
description:        "High tech, low life"
keywords:           "technology"
logo_text:          "Ishikawa Nakamura"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
url:                https://i5h1.github.io # main url
baseurl:            null # for gh-pages
enforce_ssl:        i5h1.github.io
github_post_dir:    https://github.com/i5h1/i5h1.github.io/blob/master/

# Site author info
author:
  name:             "Ishikawa Nakamura"
  email:            ishi@gmail.com
  github_username:  i5h1
  twitter_username: none
  facebook_url:     none

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   hnbloggithub

# GA
google_analytics_code: UA-58296043-7

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           Europe/Berlin
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

gems:
  - jekyll-sitemap
